name: Model Training and Evaluation

on:
  push:
    branches:
      - main  # Change this to your default branch if necessary

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Specify the version of Python you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Use requirements.txt

      - name: Run Model Training
        run: |
          # Ensure the MLflow server is running
          nohup mlflow server --host 0.0.0.0 --port 5000 &
          sleep 5  # Wait for MLflow server to start
          python model_train.py  # Replace with the name of your training script

      - name: Run Model Evaluation
        run: python evaluate.py  # Replace with the name of your evaluation script

      - name: Upload reports
        uses: actions/upload-artifact@v3
        with:
          name: data-drift-report
          path: reports/data_drift_report.html
